primernumero= float(input("ingrese el primer numero:"))
segundonumero= float(input("ingrese el segundo numero:"))
print("resultado de la suma:")
print(primernumero+segundonumero)
print("resultado de la resta:")
print(primernumero-segundonumero)
print("resultado de la multiplicacion:")
print(primernumero*segundonumero)
print("resultado de la division:")
print(primernumero/segundonumero)